### ISSUE TITLE
lib.pygeos.shared.TopologyException: found non noded intersection

### ISSUE THREAD

**Issue by vvoovv** [prochitecture/blosm#25]
Occurs for the file _facade_visibility/manhattan_01.osm_.

**Comment by vvoovv** [comment]
Also a number of non noded intersections for the file _facade_visibility/krasnaya_polyana.osm_

**Comment by vvoovv** [comment]
Also for the file _feature_detection/tula_bay_windows_02.osm_

**Comment by vvoovv** [comment]
Also for the file _facade_visibility/husum_altstadt.osm_.

**Comment by polarkernel** [comment]
A lot of bugs at very different code positions. PyGEOS checks these quite rigorously so that issues arise now, that were unseen before. I will solve them one after the other. At least I already know where they arise:

**manhattan_01.osm:**
I use an algorithm that joins all buildings to a block, when they are connected by shared edges, as provided by the function `building.polygon.edgeInfo()`, when `skipShared=True`. This algorithm gets confused when there are undetected shared edges with common vertices, as it is the case for two adjacent buildings (see red arrows below) in this scene. It would be best when this could be fixed already in the class `BldgPolygon`.

<img src="https://user-images.githubusercontent.com/48180714/147412983-fe65e6f3-1e5a-4a9f-925d-63c5dfa45ed5.png" width="450">

**krasnaya_polyana.osm:**
Here, the error comes from the pending problem of a graph-cycle within another graph-cycle, and this with many dead-end ways. 

**tula_bay_windows_02.osm and husum_altstadt.osm:**
Here the clipping algorithm for the scene border produces unwanted tails at one corner.

**Comment by vvoovv** [comment]
> This algorithm gets confused when there are undetected shared edges with common vertices, as it is the case for two adjacent buildings (see red arrows below) in this scene. It would be best when this could be fixed already in the class `BldgPolygon`.

I think that does the module _action.straight_angles_. I've just copied the latest version of it and some other modules from _dev_ to _straight_angles_.

To use it add the line `buildings.addAction(StraightAngles())` to the file _setup/mpl_blosm.py_.

**Comment by polarkernel** [comment]
> I think that does the module action.straight_angles. I've just copied the latest version of it and some other modules from dev to straight_angles.
To use it add the line buildings.addAction(StraightAngles()) to the file setup/mpl_blosm.py.

Yes, this was the reason. The file manhattan_01.osm runs now without issues. Thanks!

**Comment by vvoovv** [comment]
_streets/rotterdam_01.osm_ produces the same exception.

**Comment by vvoovv** [comment]
Can you get any result for _streets/milano_01.osm_?
It runs for endlessly.

**Comment by polarkernel** [comment]
> Can you get any result for streets/milano_01.osm?
It runs for endlessly.

I can't let it run currently, as I'm in the middle of a solution to the problem that occured in _krasnaya_polyana.osm_. I put this issue on my to-do list.

**Comment by polarkernel** [comment]
> krasnaya_polyana.osm:
Here, the error comes from the pending problem of a graph-cycle within another graph-cycle, and this with many dead-end ways.

I committed a version that solves this problem. It was caused by a way to an way-island, which was removed erroneously by the dead-end algorithm. The reason is complicated, I described it in a long comment, starting at line [311](https://github.com/prochitecture/blosm/blob/204ecce102845d69e8e5894fd8c86ada028d969a/action/road_polygons.py#L311). The green arrow in the image below shows this way.

The dataset executes now completely but it takes very long. The reason is the large graph-cycle painted in red in the image below. The circumscribed circle around this cycle is very large and includes most of the polyline objects in the scene. Their subtraction therefore takes a lot of processing time in PyGeos. The result is a large polygon with a large number of holes, which again takes a large execution time for the decomposition. I don't yet know how to solve this issue.

<img src="https://user-images.githubusercontent.com/48180714/147582710-a99b15ad-74ba-4747-a258-087d95420155.png" width="500">

Other issues solved in this commit:

- Dead-end ways are now excluded from the initial processing of graph-cycles.
- Linear polyline objects are no more subtracted from graph-cycles.

**Comment by vvoovv** [comment]
> Yes, this was the reason. The file manhattan_01.osm runs now without issues. Thanks!

However the subdivision is still not created for that graph-cycle:

![image](https://user-images.githubusercontent.com/613295/147652044-b3620c1b-f259-489d-816c-5d9a1e38a983.png)

What is still wrong with the buildings inside the graph-cycle?

I traced the common border of those two buildings to create a single building and removed the existed buildings. The subdivision was created for that case:

![image](https://user-images.githubusercontent.com/613295/147652925-7238eac1-acdb-4cbb-8c6c-4573c753bbec.png)

**Comment by polarkernel** [comment]
> However the subdivision is still not created for that graph-cycle:

There was a bug in the polygon decomposition, while its exception was silently chatched. Fixed and committed. Now exceptions there produce an error text.

**Comment by vvoovv** [comment]
Are all problems solved for this issue? Can we close it?

**Comment by polarkernel** [comment]
> Are all problems solved for this issue? Can we close it?

I see no more errors of this kind, the issue can be closed.
