### ISSUE TITLE
Ambiguous connectors due to way-loops at cluster ends

### ISSUE THREAD

**Issue by polarkernel** [prochitecture/blosm#54]
Currently, the connectors of an `IntersectionArea` are stored in a dictionary, where the key of this dictionary is the ID of the corresponding way-section key in the dictionary of `TrimmedWaySection`:

```Python
        # The connectors of this polygon to the way-sections.
        # A dictionary of tuples, where the key is the ID of the corresponding
        # way-section key in the dictionary of TrimmedWaySection. The tuple has two
        # elements, <indx> and <end>. <indx> is the first index in the intersection
        # polygon for this connector, the second index is <indx>+1. <end> is
        # the type 'S' for the start or 'E' for the end of the TrimmedWaySection
        # connected here.
        self.connectors = dict()
```
I have now come across a case where a way makes a loop from and into the same area. The `TrimmedWaySection` with the key 73 produces two connectors that can't both be stored with the same key in `self.connectors`:

<img src="https://user-images.githubusercontent.com/48180714/225353606-8752a74f-a4dd-4799-8559-075aa510f2e6.png" width="250">

The question now is how to fix this in the best possible way, with regard to its use in Blender.

**Comment by polarkernel** [comment]
One possibility would be to use a tuple as a key that contains either 'S' for the start of the way or 'E' for its end:
```Python
        area.connectors[(73,'S')]
        area.connectors[(73,'E')]
```

**Comment by vvoovv** [comment]
I suggest to buy two properties in the key of the dictionary `connectors` for the price of one.

The absolute value of the key is always the ID of a way-section or way-cluster. If the key is positive than the way-section or way-cluster starts at the connector, otherwise it ends at the connector.

The second property in an entry of the dictionary which can have a value of _E_ or _S_ will be not needed anymore.

The key can't be equal to zero.

**Comment by polarkernel** [comment]
I love sparse solutions, thanks for this idea! The zero is no problem, I can easily let start the way-section index at one. I will implement this solution with the next update. I am close to have a solution for the overlapping out-ways at cluster ends.

**Comment by vvoovv** [comment]
Can this issues be closed?

**Comment by vvoovv** [comment]
File _berlin_karl_marx_allee.osm_
The dictionary `wayClusters` contains a cluster with the index _0_ which leads to weird results.

**Comment by polarkernel** [comment]
> The dictionary wayClusters contains a cluster with the index 0 which leads to weird results.

Sorry. This bug is fixed by the last commit.

**Comment by vvoovv** [comment]
Another issue with the latest commit.

There is a connector entry `intersectionAreas[21].connectors[-29]`. The key _-29_ means that the way-section `waySectionLines[29]` ends at the intersection. But it actually starts there.

```python
waySectionLines[29].centerline = [
  Vector( (-73.12081146240234, 51.03520584106445) ),
  Vector( (-72.4212417602539, 55.73343276977539) )
]
```

![image](https://user-images.githubusercontent.com/613295/226138543-e0275f97-8229-4b23-9787-a0af52bc0ff6.png)

**Comment by vvoovv** [comment]
Also, why does `intersectionAreas[21]` have so many points?

**Comment by polarkernel** [comment]
> There is a connector entry intersectionAreas[21].connectors[-29]

I am sorry, It's weird, I can't reproduce that:
```Python
attrs = vars(manager.intersectionAreas[21])
print(', '.join("%s: %s" % item for item in attrs.items()))

polygon: [Vector((183.5948944091797, -76.53007507324219)), Vector((183.355712890625, ...]
, connectors: {77: 1}
, clusterConns: {-23: 3, 24: 5}
, numPoints: 0
, connectorsInfo: None
```

**Comment by vvoovv** [comment]
> I am sorry, It's weird, I can't reproduce that:

Did you try it on _berlin_karl_marx_allee.osm_?

I tried it on _berlin_karl_marx_allee.osm_ in the command line mode.

Below is the output for me:

```python
attrs = vars(manager.intersectionAreas[21])
print(', '.join("%s: %s" % item for item in attrs.items()))
polygon: [Vector((-81.65096282958984, 31.91581153869629)), ...],
connectors: {-21: 0, -29: 10},
clusterConns: {},
numPoints: 0,
connectorsInfo: None
```

**Comment by polarkernel** [comment]
> Did you try it on berlin_karl_marx_allee.osm?

Oh, sorry, I thought you were working with the new _moscow_leningradski_prospekt_edited.osm_.

The bug with the way-directions is fixed. The high number of vertices comes from spline construction. This is very old code, where I tried to create smooth width transitions to make them as realistic as possible. With the new commit, I reduced the number of vertices per side from 10 to 5 (line [505](https://github.com/prochitecture/blosm/blob/abba7a4ada137d510220096ddc2f99f69dcd8094/way/way_intersections.py#L505) in _/way/way_intersections.py_).

**Comment by vvoovv** [comment]
There is still an issue with that intersection:

```python
manager.intersectionAreas[21].connectors[29]: 10
```

But
```
len(manager.intersectionAreas[21].polygon): 10
```

The index `manager.intersectionAreas[21].connectors[29]` is larger than the largest possible index _9_ in `manager.intersectionAreas[21].polygon`.

**Comment by polarkernel** [comment]
> There is still an issue with that intersection:

Sorry, fixed version is committed.

I am sorry for this kind of mistake. I am constantly working on an experimental version of the code, but do not want to commit it yet. When I have fixed and tested a bug like the last one in the experimental version (because it is instrumented with a lot of debug plots) I have to port it to a new version cloned from the repository. But then I run the risk of not completing the transfer.

**Comment by vvoovv** [comment]
Another set of issues with _berlin_karl_marx_allee.osm_.

The way-cluster manager.wayClusters[19] ends at the intersection `manager.intersectionAreas[8]`

```python
manager.intersectionAreas[8].clusterConns: {
  -19: 3,
  20: 5
}
```

However,
```python
manager.wayClusters[19].endConnected: False
```

**Comment by polarkernel** [comment]
> Another set of issues with berlin_karl_marx_allee.osm.

Fixed and committed.

**Comment by vvoovv** [comment]
> I am sorry for this kind of mistake.

I'd suggest using Git's branching and merging actively.

Create a new local branch for a experiment:
```
git checkout -b experiment
```

Commit the code to the branch `experiment`.

If the experiment was successful, merge the branch `experiment` to `streets_for_gn`:
```
git checkout streets_for_gn
git merge experiment
git branch -D experiment
```

If the experiment was unsuccessful, simple delete the branch `experiment`:
```
git branch -D experiment
```

If there is a need to fix a bug in the branch `streets_for_gn`, commit it and then merge it to the branch `experiment`:
```
git merge streets_for_gn
```
I expect that the merge will be automatical.

**Comment by polarkernel** [comment]
> I'd suggest using Git's branching and merging actively.

Thanks for these instructions, I'll give them a try. The management for Git is currently handled by my development environment (Visual Studio Code). I'm just afraid of using manual Git instructions, it's made a mighty mess in VS-Code for me once before. But for this experiment, I can keep the results locally when I test your instructions. That way it will be easy to remove them in case of troubles.

**Comment by vvoovv** [comment]
> I'll give them a try.

To revert the last commit use:
```
git reset HEAD~1
```
or
```
git reset --hard HEAD~1
```
The latter also removes the entry in the git's history

**Comment by vvoovv** [comment]
I merged `dev` into `street_for_gn`.

The most visible change is that _0_ is written instead of _'S'_ and _-1_ instead of _'E'_ in `IntersectionArea.getConnectorsInfo`. The related values can be used right away in the list `centerline`.
